### ISSUE TITLE
Metadata-flavour. 

### ISSUE THREAD

**Issue by r3dpars3c** [seadog007/noxCTF-2018-PSRF-as-Pwn#2]
Hey but the endpoint you have mentioned at first
http://metadata.google.internal/computeMetadata/v1beta1/instance/service-accounts/default/token&method=get

This endpoint also requires the header Metadata-Flavour : Google. 

But you didn't provided in the first curl request.  How is this possible ??????????

**Comment by seadog007** [comment]
Hi,

v1beta1 doesn't require additional header during the event (2018), you might be able to find other bug bounty writeup for this.
Hope this can answer your question.

Thanks
